# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
      - '*.*'

resources:
  - repo: self

variables:
  tag: 'dashboard-$(Build.SourceBranchName)'
  repoServiceConnection: 'akaDockerRegistryServiceConnection'
  imageName: 'sagtestclient/aron-docker'

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: BuildAndPublish
      displayName: Build and Publish
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Build image
          inputs:
            repository: $(imageName)
            command: build
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(tag)
              $(Build.BuildNumber)
        - task: Docker@2
          displayName: Push image to repo
          condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
          inputs:
            containerRegistry: $(repoServiceConnection)
            repository: $(imageName)
            command: push
            tags: |
              $(tag)

